#!/bin/sh
#
#  tianqiKeepStart.sh
#
#  Automatic generated by fboxtool
#
#  Created by 吴道睿 on 2018-11-15 15:16:12
#

while :
do
#  3秒检测一次
    sleep 3
    RESULT=`ps -e|grep 'tianqi'|sed -e "/grep/d"` 
    if [ -z "$RESULT" ];then 
       # 启动进程 默认http模式启动 
       (./tianqi -mode http >>err.dat &)
       echo "$(date)  _restart_" >> tianqiRestart.log
    fi
done
